### ISSUE TITLE
10/08_어른이의 싱크빅팀 일정

### ISSUE THREAD

**Issue by jintae-choi** [2021-SMHRD-KDT-New-AI-1/thinkBig#1]
감자 : 프로젝트 총괄
양파 : DB
고구마 : Nodejs
옥수수 : UI/UX, Android
가지 : UI/UX, Android

금일 할당량은
1. DB 설계
2. UI 설계
3. Nodejs 값 주고받기

**Comment by yunivearth** [comment]
ㅇㅇㅇㅇㅇ
